<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $permissions =[
            ['name'=>'create_employee','guard_name'=>'web','display_name'=>'Create Employee','Category'=>'Employee'],
            ['name'=>'update_employee','guard_name'=>'web','display_name'=>'Update Employee','Category'=>'Employee'],
            ['name'=>'view_employee','guard_name'=>'web','display_name'=>'View Employee','Category'=>'Employee'],
            ['name'=>'delete_employee','guard_name'=>'web','display_name'=>'Delete Employee','Category'=>'Employee'],
            ['name'=>'manage_earning','guard_name'=>'web','display_name'=>'Manage Earning','Category'=>'Payroll'],
            ['name'=>'manage_deduction','guard_name'=>'web','display_name'=>'Manage Deductions','Category'=>'Payroll'],
            ['name'=>'manage_allowance','guard_name'=>'web','display_name'=>'Manage Allowance','Category'=>'Payroll'],
            ['name'=>'manage_relief','guard_name'=>'web','display_name'=>'Manage Relief','Category'=>'Payroll'],
            ['name'=>'manage_benefit','guard_name'=>'web','display_name'=>'Manage Benefits','Category'=>'Payroll'],
            ['name'=>'process_payroll','guard_name'=>'web','display_name'=>'Process Payroll','Category'=>'Payroll'],
            ['name'=>'view_payroll_report','guard_name'=>'web','display_name'=>'View Payroll Report','Category'=>'Payroll'],
            ['name'=>'manage_settings','guard_name'=>'web','display_name'=>'Manage Settings','Category'=>'Payroll'],
            ['name'=>'view_application','guard_name'=>'web','display_name'=>'View Application','Category'=>'Leave'],
            ['name'=>'amend_application','guard_name'=>'web','display_name'=>'Amend Application','Category'=>'Leave'],
            ['name'=>'approve_application','guard_name'=>'web','display_name'=>'Approve Application','Category'=>'Leave'],
            ['name'=>'reject_application','guard_name'=>'web','display_name'=>'Reject Application','Category'=>'Leave'],
            ['name'=>'cancel_application','guard_name'=>'web','display_name'=>'Cancel Application','Category'=>'Leave'],
            ['name'=>'manage_type','guard_name'=>'web','display_name'=>'Manage Leave Types','Category'=>'Leave'],
            ['name'=>'view_leave_report','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Leave'],
            ['name'=>'manage_organization','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Organization'],
            ['name'=>'manage_branch','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Organization'],
            ['name'=>'manage_group','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Organization'],
            ['name'=>'manage_organization_settings','guard_name'=>'web','display_name'=>'manage settings','Category'=>'Organization'],
            ['name'=>'manage_user','guard_name'=>'web','display_name'=>'Manage User','Category'=>'System'],
            ['name'=>'manage_role','guard_name'=>'web','display_name'=>'Manage Role','Category'=>'System'],
            ['name'=>'manage_audit','guard_name'=>'web','display_name'=>'Manage Audit','Category'=>'System'],
            ['name'=>'confirm_payments','guard_name'=>'web','display_name'=>'Confirm Payments','Category'=>'Payments'],
            ['name'=>'confirm_stock','guard_name'=>'web','display_name'=>'Confirm Stock','Category'=>'Stock'],
            ['name'=>'authorize_purchase_order','guard_name'=>'web','display_name'=>'Authorize Purchase Order','Category'=>'Purchase'],
            ['name'=>'review_purchase_order','guard_name'=>'web','display_name'=>'Review Purchase Order','Category'=>'Purchase'],
            ['name'=>'create_item','guard_name'=>'web','display_name'=>'Create Item','Category'=>'Items'],
            ['name'=>'update_item','guard_name'=>'web','display_name'=>'Update Item','Category'=>'Items'],
            ['name'=>'view_item','guard_name'=>'web','display_name'=>'View Item','Category'=>'Items'],
            ['name'=>'delete_item','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Items'],
            ['name'=>'create_client','guard_name'=>'web','display_name'=>'Create Client','Category'=>'Clients'],
            ['name'=>'update_client','guard_name'=>'web','display_name'=>'Update Client','Category'=>'Clients'],
            ['name'=>'delete_client','guard_name'=>'web','display_name'=>'Delete Client','Category'=>'Clients'],
            ['name'=>'view_client','guard_name'=>'web','display_name'=>'View Client','Category'=>'Clients'],
            ['name'=>'create_payments','guard_name'=>'web','display_name'=>'Create Payment','Category'=>'Payments'],
            ['name'=>'update_payments','guard_name'=>'web','display_name'=>'Update Payment','Category'=>'Payments'],
            ['name'=>'delete_payments','guard_name'=>'web','display_name'=>'Delete Payment','Category'=>'Payments'],
            ['name'=>'view_daily_payments','guard_name'=>'web','display_name'=>'view daily payments','Category'=>'Payments'],
            ['name'=>'create_payment_methods','guard_name'=>'web','display_name'=>'create payment methods','Category'=>'Payments'],
            ['name'=>'update_payment_methods','guard_name'=>'web','display_name'=>'Update payment methods','Category'=>'Payments'],
            ['name'=>'delete_payment_methods','guard_name'=>'web','display_name'=>'Delete Payment Methods','Category'=>'Payments'],
            ['name'=>'create_purchase_order','guard_name'=>'web','display_name'=>'Create Purchase Order','Category'=>'Purchase'],
            ['name'=>'view_purchase_order','guard_name'=>'web','display_name'=>'View Purchase Order','Category'=>'Purchase'],
            ['name'=>'cancel_purchase_order','guard_name'=>'web','display_name'=>'Cancel Purchase Order','Category'=>'Purchase'],
            ['name'=>'create_sale_order','guard_name'=>'web','display_name'=>'Create Sale Order','Category'=>'Sales'],
            ['name'=>'view_sale_order','guard_name'=>'web','display_name'=>'View Sale Order','Category'=>'Sales'],
            ['name'=>'cancel_sale_order','guard_name'=>'web','display_name'=>'Cancel Sale Order','Category'=>'Sales'],
            ['name'=>'approve_delivered_sale_order','guard_name'=>'web','display_name'=>'approve delivered sale order','Category'=>'Sales'],
            ['name'=>'approve_delivered_purchase_order','guard_name'=>'web','display_name'=>'Approve Delivered Purchase Order','Category'=>'Purchase'],
            ['name'=>'create_sale_target','guard_name'=>'web','display_name'=>'Create Sale Target','Category'=>'Sales'],
            ['name'=>'update_sale_target','guard_name'=>'web','display_name'=>'Update Sale Target','Category'=>'Sales'],
            ['name'=>'delete_sale_target','guard_name'=>'web','display_name'=>'Delete Sale Target','Category'=>'Sales'],
            ['name'=>'create_quotation','guard_name'=>'web','display_name'=>'Create Quotation','Category'=>'Quotation'],
            ['name'=>'view_quotation','guard_name'=>'web','display_name'=>'View Quotation','Category'=>'Quotation'],
            ['name'=>'approve_quotation','guard_name'=>'web','display_name'=>'Approve Quotation','Category'=>'Quotation'],
            ['name'=>'reject_quotation','guard_name'=>'web','display_name'=>'Reject Quotation','Category'=>'Quotation'],
            ['name'=>'edit_quotation','guard_name'=>'web','display_name'=>'Edit Quotation','Category'=>'Quotation'],
            ['name'=>'receive_stock','guard_name'=>'web','display_name'=>'Receive Stock','Category'=>'Stock'],
            ['name'=>'track_stock','guard_name'=>'web','display_name'=>'Track Stock','Category'=>'Stock'],
            ['name'=>'lease_item','guard_name'=>'web','display_name'=>'Lease Item','Category'=>'Stock'],
            ['name'=>'create_store','guard_name'=>'web','display_name'=>'Create Store','Category'=>'Store'],
            ['name'=>'update_store','guard_name'=>'web','display_name'=>'Update Store','Category'=>'Store'],
            ['name'=>'delete_store','guard_name'=>'web','display_name'=>'Delete Store','Category'=>'Store'],
            ['name'=>'create_tax','guard_name'=>'web','display_name'=>'Create Tax','Category'=>'Tax'],
            ['name'=>'update_tax','guard_name'=>'web','display_name'=>'Update Tax','Category'=>'Tax'],
            ['name'=>'delete_tax','guard_name'=>'web','display_name'=>'Delete Tax','Category'=>'Tax'],
            ['name'=>'view_erp_reports','guard_name'=>'web','display_name'=>'View ERP Reports','Category'=>'Erp Reports'],
            ['name'=>'create_driver','guard_name'=>'web','display_name'=>'Create Driver','Category'=>'Driver'],
            ['name'=>'update_driver','guard_name'=>'web','display_name'=>'Update Driver','Category'=>'Driver'],
            ['name'=>'view_driver','guard_name'=>'web','display_name'=>'View Driver','Category'=>'Driver'],
            ['name'=>'delete_driver','guard_name'=>'web','display_name'=>'Delete Driver','Category'=>'Driver'],
            ['name'=>'create_vehicle','guard_name'=>'web','display_name'=>'Create Vehicles','Category'=>'Vehicle'],
            ['name'=>'update_vehicle','guard_name'=>'web','display_name'=>'Update Vehicles','Category'=>'Vehicle'],
            ['name'=>'view_vehicle','guard_name'=>'web','display_name'=>'View Vehicle','Category'=>'Vehicle'],
            ['name'=>'delete_vehicle','guard_name'=>'web','display_name'=>'Delete Vehicles','Category'=>'Vehicle'],
            ['name'=>'assign_driver','guard_name'=>'web','display_name'=>'Assign Vehicle','Category'=>'Assign Driver'],
            ['name'=>'update_assigned_driver','guard_name'=>'web','display_name'=>'Update Assigned Driver','Category'=>'Assign Driver'],
            ['name'=>'view_assigned_driver','guard_name'=>'web','display_name'=>'View Assigned Driver','Category'=>'Assign Driver'],
            ['name'=>'remove_assigned_driver','guard_name'=>'web','display_name'=>'Remove Assigned Driver','Category'=>'Assign Driver'],
            ['name'=>'view_store','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Store'],
            ['name'=>'view_tax','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Tax'],
            ['name'=>'create_pricing','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Pricing'],
            ['name'=>'update_pricing','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Pricing'],
            ['name'=>'view_pricing','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Pricing'],
            ['name'=>'delete_pricing','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Pricing'],
            ['name'=>'view_stock','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Stock'],
            ['name'=>'view_sale_target','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Sales'],
            ['name'=>'view_payment_methods','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Payments'],
            ['name'=>'view_payments','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Payments'],
            ['name'=>'generate_invoice','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Quotation'],
            ['name'=>'confirm_update_item','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Items'],
            ['name'=>'view_account','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Accounts'],
            ['name'=>'create_account','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Accounts'],
            ['name'=>'update_account','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Accounts'],
            ['name'=>'delete_account','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Accounts'],
            ['name'=>'confirm_item_update','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Items'],
            ['name'=>'confirm_pricing_update','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Pricing'],
            ['name'=>'view_expense','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Expenses'],
            ['name'=>'create_expense','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Expenses'],
            ['name'=>'update_expense','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Expenses'],
            ['name'=>'delete_expense','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Expenses'],
            ['name'=>'view_petty_cash','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Petty Cash'],
            ['name'=>'create_new_transaction','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Petty Cash'],
            ['name'=>'view_expense_claim','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Expense Claim'],
            ['name'=>'update_expense_claim','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Expense Claim'],
            ['name'=>'create_new_receipt','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Expense Claim'],
            ['name'=>'approve_expense_claim','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Expense Claim'],
            ['name'=>'decline_expense_claim','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Expense Claim'],
            ['name'=>'pay_expense_claim','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Expense Claim'],
            ['name'=>'view_asset_management','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Asset Management'],
            ['name'=>'create_asset_management','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Asset Management'],
            ['name'=>'update_asset_management','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Asset Management'],
            ['name'=>'depreciation','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Asset Management'],
            ['name'=>'dispose_asset','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Asset Management'],
            ['name'=>'delete_asset','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Asset Management'],
            ['name'=>'transfer_money','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Petty Cash'],
            ['name'=>'receive_money','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Petty Cash'],
            ['name'=>'email_purchase_order','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'Petty Cash'],
            ['name'=>'view_users','guard_name'=>'web','display_name'=>'Manage Holiday','Category'=>'System'],
        ];
        Permission::insert($permissions);
    }
}
